kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dinner-bell
subjects:
- kind: ServiceAccount
  name: dinner-bell
  namespace: dinner-bell
roleRef:
  kind: ClusterRole
  name: dinner-bell
  apiGroup: rbac.authorization.k8s.io
